### ISSUE TITLE
Version 0.4.1

### ISSUE THREAD

**Issue by TigerWolf** [nicolai86/ansible-prepare-release#11]
When are you planning to release 0.4.1 to Ansible Galaxy?

https://galaxy.ansible.com/detail#/role/302

Only 0.4.0 is showing up.

**Comment by nicolai86** [comment]
Ansible Galaxy has always leaked behind b/c I myself don't use it. But I'll push the new version later today. 

Thanks for remjnding!

**Comment by DireMunchkin** [comment]
What happened with this? I would also like to use v.0.4.1, would be cool if you could upload it to Galaxy.

**Comment by nicolai86** [comment]
@keiter it's updated now!
